#!/usr/bin/perl
use strict;
use utf8;
use Data::Dumper;
use FindBin;
use Daemon::Control;

use lib $FindBin::RealBin . '/lib';
use CyberFT::Utils;

# Прочитаем конфигурационный файл.
my $cfg = CyberFT::Utils::read_app_config();
unless (defined $cfg) {
    die "Error reading config file (config/cyberft.cfg)";
}
unless (defined $cfg->{pid_file_forwarder} && $cfg->{pid_file_forwarder} =~ /\S+/) {
    die "Error reading required config parameter: pid_file_forwarder";
}
unless (defined $cfg->{workers_forwarder}) {
    die "Error reading required config parameter: workers_forwarder";
}
unless ($cfg->{workers_forwarder} =~ /^\d+$/ && $cfg->{workers_forwarder} > 0 && $cfg->{workers_forwarder} < 100) {
    die "Bad value of config parameter: workers_forwarder";
}

my $stderr_file = '/dev/null';
if (defined $cfg->{stderr_file} && $cfg->{stderr_file} =~ /\S+/) {
    $stderr_file = $cfg->{stderr_file};
}

for my $procid (1 .. $cfg->{workers_forwarder}) {
    Daemon::Control->new(
        name         => "CyberFT Forwarder #$procid",
        scan_name    => qr/cyberft_forwarder/,
        kill_timeout => 3,
        path         => $FindBin::RealBin,
        program      => $FindBin::RealBin . "/scripts/cyberft_forwarder.pl --procid=$procid",
        pid_file     => $cfg->{pid_file_forwarder} . ".$procid",
        stdout_file  => '/dev/null',
        stderr_file  => $stderr_file,
    )->run_command(@ARGV);
}
